setwd("G:\\My Drive\\Chapter 3/GVAR")
source("vardata_format.R")
source("BVAR_estimation_NIW.R")
source("BVAR_estimation_flat.R")
source("aux_functions.R")
source("set_dummy_obs_prior.R")
source("BVAR_chol_irf.R")
source("Stack_attack.R")
source("star_variables.R")
#source("BVAR_draw.R")
#source("VAR_data_prep.R")
#source("VAR_estimate.R")
library(expm)
